### ISSUE TITLE
`failed crypt check` error

### ISSUE THREAD

**Issue by smarj** [charmbracelet/skate#23]
This isn't the first time I've rebooted my (macOS 12.2.1) client, but after rebooting today a `skate get` or `skate list` command responds with this:

```
➜ skate list         
Error: failed crypt check
Usage:
   list [@DB] [flags]

Flags:
  -d, --delimiter string   delimiter to separate keys and values (default "\t")
  -h, --help               help for list
  -k, --keys-only          only print keys and don't fetch values from the db
  -r, --reverse            list in reverse lexicographic order
  -v, --values-only        only print values

failed crypt check
```

My SSH key works fine elsewhere. Another (Linux) host I hooked up returns the same error.

**Comment by toby** [comment]
Hi! This should be fixed in a soon to release update to the underlying charm/kv library. I'll leave the issue open and ping you when when it's out (should be this week).

**Comment by smarj** [comment]
It's not longer giving me a `failed crypt check` with 0.1.4 from homebrew. Now I get a segfault on macOS and Linux:

```
➜ skate list @[dbname].db
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14f1426]

goroutine 1 [running]:
github.com/dgraph-io/badger/v3.(*DB).MaxVersion(0xc000304000)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2011.1/db.go:373 +0x46
github.com/charmbracelet/charm/kv.(*KV).Sync(0xc000694720)
	/home/runner/go/pkg/mod/github.com/charmbracelet/charm@v0.10.0/kv/kv.go:109 +0x25
main.list(0x1f61b60, {0xc0002eccc0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/charmbracelet/skate@v0.1.4/main.go:150 +0x12b
github.com/spf13/cobra.(*Command).execute(0x1f61b60, {0xc0002ecca0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1f610e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/skate@v0.1.4/main.go:283 +0x25
```

**Comment by toby** [comment]
Ok thanks for reporting. Can you [grab](https://github.com/charmbracelet/charm#installation) the latest `charm` binary and run: `charm migrate-account`. That _should_ fix it, but please let me know if it's still not working.

**Comment by smarj** [comment]
Thanks, the `charm migrate-account` worked.
