### ISSUE TITLE
Skate commands failing on Mac 12.2.1

### ISSUE THREAD

**Issue by msiege2** [charmbracelet/skate#27]
When running any skate command (on multiple different Macbooks) I get a panic and failure.  This worked on first install, haven't used skate in a few weeks, and now it is failing.

Skate v.1.4.0 installed via homebrew, MacOS 12.2.1.

Example command: `skate list`

Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14f1426]

goroutine 1 [running]:
github.com/dgraph-io/badger/v3.(*DB).MaxVersion(0xc0006f8000)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2011.1/db.go:373 +0x46
github.com/charmbracelet/charm/kv.(*KV).Sync(0xc0005cc3c0)
	/home/runner/go/pkg/mod/github.com/charmbracelet/charm@v0.10.0/kv/kv.go:109 +0x25
main.list(0x1f61b60, {0x1f9ea30, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/charmbracelet/skate@v0.1.4/main.go:150 +0x12b
github.com/spf13/cobra.(*Command).execute(0x1f61b60, {0x1f9ea30, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1f610e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/skate@v0.1.4/main.go:283 +0x25
```

**Comment by toby** [comment]
Hi! We made some changes to the charm/kv backend. Can you try downloading the latest `charm` release from here: https://github.com/charmbracelet/charm

Then running `charm migrate-account`. That should fix this issue.

**Comment by msiege2** [comment]
That worked!

**Comment by toby** [comment]
Awesome!! Thanks for the report.
